### ISSUE TITLE
Error running this command: fqtools count 

### ISSUE THREAD

**Issue by mansi-aai** [iqbal-lab-org/clockwork#123]
Hello ! 
I'm attempting a test run, but I've encountered an error for which I couldn't locate any pertinent information. Here are the details. Any insights or guidance would be greatly appreciated.  Thank you !
```

(mtb) root@ip:/attach/data/mtb/WHO_pipeline# singularity exec clockwork_container.img clockwork map_reads \
  --unsorted_sam SAMEA2534421 Ref.remove_contam/ref.fa SAMEA2534421.sam \
  SAMEA2534421/ERR552113_1.fastq.gz SAMEA2534421/ERR552113_2.fastq.gz
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.1.0) or chardet (5.2.0) doesn't match a supported v
ersion!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
[2023-12-03T18:33:57 - clockwork map_reads - INFO] Run command: fqtools count SAMEA2534421/ERR552113_1.fastq.gz SAMEA2534421/ERR552113_2.fastq.gz
[2023-12-03T18:33:57 - clockwork map_reads - INFO] Return code: 1
Error running this command: fqtools count SAMEA2534421/ERR552113_1.fastq.gz SAMEA2534421/ERR552113_2.fastq.gz
Return code: 1
Output from stdout:

Output from stderr:
ERROR: failed to initialize IO

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.12.3-py3.8.egg/clockwork/fqtools.py", line 17, in count
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.12.3-py3.8.egg/clockwork/utils.py", line 38, in syscall                       [0/1491]
Exception: Error in system call. Cannot continue

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.12.3-py3.8.egg/clockwork/read_map.py", line 22, in map_reads
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.12.3-py3.8.egg/clockwork/fqtools.py", line 19, in count
Exception: Error running fqtools count SAMEA2534421/ERR552113_1.fastq.gz SAMEA2534421/ERR552113_2.fastq.gz

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/clockwork", line 4, in <module>
    __import__('pkg_resources').run_script('clockwork==0.12.3', 'clockwork')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.12.3-py3.8.egg/EGG-INFO/scripts/clockwork", line 1008, in <module>
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.12.3-py3.8.egg/clockwork/tasks/map_reads.py", line 13, in run
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.12.3-py3.8.egg/clockwork/read_map.py", line 133, in map_reads_set
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.12.3-py3.8.egg/clockwork/read_map.py", line 24, in map_reads
Exception: Error counting reads in input files SAMEA2534421/ERR552113_1.fastq.gz SAMEA2534421/ERR552113_2.fastq.gz
```

db.ini file : 
```
[db_login]
user = root
password = password
host = localhost
db = clockwork
```

To @martinghunt / @Zhicheng-Liu / @mbhall88 / @ffranr

**Comment by martinghunt** [comment]
My guess is that the fastq file(s) were not found or are empty. Does this work?

```
singularity exec clockwork_container.img ls -lh SAMEA2534421/ERR552113_1.fastq.gz SAMEA2534421/ERR552113_2.fastq.gz
```

**Comment by mansi-aai** [comment]
@martinghunt Thank you for your response but this did not work.

**Comment by martinghunt** [comment]
What was the output?

**Comment by mansi-aai** [comment]
@martinghunt 

```
(mtb) root@ip:/attach/data/test1# singularity exec clockwork_v0.12.3.img ls -lh SAMEA2534421/ERR552113_1.fastq.gz SAMEA2534421/ERR552113_2.fastq.gz
/usr/bin/ls: cannot access 'SAMEA2534421/ERR552113_1.fastq.gz': No such file or directory
/usr/bin/ls: cannot access 'SAMEA2534421/ERR552113_2.fastq.gz': No such file or directory

(mtb) root@ip:/attach/data/test1# ls SAMEA2534421/
ERR552113_1.fastq.gz ERR552113_2.fastq.gz

```

**Comment by martinghunt** [comment]
This means your singularity install isn't by default seeing `CWD` when you run it. By default it should. The docs are here:

https://docs.sylabs.io/guides/latest/user-guide/bind_paths_and_mounts.html

Could try looking at the examples with `--bind` in there? Or setting `$SINGULARITY_BIND` to something like `/attach/data`?

**Comment by mansi-aai** [comment]
@martinghunt It worked out. One quick question , Does this pipeline works on single end fastq input also ?

Many thanks,
Mansi

**Comment by martinghunt** [comment]
Sorry, slow reply to this - it's paired reads only
