### ISSUE TITLE
problem with reference_prepare for remove_contam

### ISSUE THREAD

**Issue by flashton2003** [iqbal-lab-org/clockwork#41]
I'm running reference_prepare for remove contam with the following command line

`singularity exec clockwork_container.img clockwork reference_prepare --contam_tsv /clockwork/reference_genomes/remove_contam.tsv --outdir Reference.remove_contam /clockwork/reference_genomes/remove_contam.fa.gz`

I left it running for 2 or 3 hours before I cancelled it, this is the message received when cancelling (not sure how useful this is):

```Traceback (most recent call last):
  File "/usr/local/bin/clockwork", line 4, in <module>
    __import__('pkg_resources').run_script('clockwork==0.5.2', 'clockwork')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1510, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/clockwork-0.5.2-py3.6.egg/EGG-INFO/scripts/clockwork", line 500, in <module>
  File "/usr/local/lib/python3.6/dist-packages/clockwork-0.5.2-py3.6.egg/clockwork/tasks/reference_prepare.py", line 29, in run
  File "/usr/local/lib/python3.6/dist-packages/clockwork-0.5.2-py3.6.egg/clockwork/reference_dir.py", line 49, in make_index_files
  File "/usr/local/lib/python3.6/dist-packages/clockwork-0.5.2-py3.6.egg/clockwork/utils.py", line 18, in syscall
  File "/usr/lib/python3.6/subprocess.py", line 405, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 830, in communicate
    stdout = self.stdout.read()
KeyboardInterrupt
```

Perhaps I'm doing something stupid?

**Comment by martinghunt** [comment]
Maybe it just hadn't finished? It can take a long time. Can you do ls -lhtr on Reference.remove_contam? It was probably running bwa index -- takes a while on that big fasta file.

**Comment by flashton2003** [comment]
Ah right, yes that was it. Sorry, didn't realise what it was doing.
