### ISSUE TITLE
error in download the reference data

### ISSUE THREAD

**Issue by dhcvn** [iqbal-lab-org/clockwork#90]
why I still met error when run command to download reference genome although I used clockwork_container.img?

**Comment by martinghunt** [comment]
Could you please paste the command you ran and the errors here?

**Comment by dhcvn** [comment]
Herewith my command I ran and result:
----------------------------------------------
singularity exec clockwork_container.img \> /clockwork/scripts/download_tb_reference_files.pl ref_data
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US",
	LC_ALL = (unset),
	LANG = "en_US.UTF-8"
 are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C"  .
------------------- download genomes --------------------
wget -nv -O AP018165.fa 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&rettype=fasta&retmode=text&id=AP018165';
2021-11-18 10:54:29 URL:https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&rettype=fasta&retmode=text&id=AP018165 [5065899] -> "AP018165.fa" [1]
enaDataGet -d tmp.93701 -f fasta JYNU00000000
Traceback (most recent call last):
 File "/bioinf-tools/enaBrowserTools-1.5.4/python3/enaDataGet.py", line 84, in <module>
 sequenceGet.download_wgs(dest_dir, accession, output_format)
 File "/bioinf-tools/enaBrowserTools-1.5.4/python3/sequenceGet.py", line 41, in download_wgs
 return download_unversioned_wgs(dest_dir, accession, output_format)
 File "/bioinf-tools/enaBrowserTools-1.5.4/python3/sequenceGet.py", line 62, in download_unversioned_wgs
 public_set_url = utils.get_nonversioned_wgs_ftp_url(prefix, utils.PUBLIC, output_format)
 File "/bioinf-tools/enaBrowserTools-1.5.4/python3/utils.py", line 452, in get_nonversioned_wgs_ftp_url
 ftp.cwd(base_dir)
 File "/usr/lib/python3.6/ftplib.py", line 631, in cwd
 return self.voidcmd(cmd)
 File "/usr/lib/python3.6/ftplib.py", line 278, in voidcmd
 return self.voidresp()
 File "/usr/lib/python3.6/ftplib.py", line 251, in voidresp
 resp = self.getresp()
 File "/usr/lib/python3.6/ftplib.py", line 246, in getresp
 raise error_perm(resp)
ftplib.error_perm: 550 Failed to change directory.
ERROR: Something unexpected went wrong please try again.
If problem persists, please contact datasubs@ebi.ac.uk for assistance, with the above error details.
Error running: enaDataGet -d tmp.93701 -f fasta JYNU00000000 at /clockwork/scripts/download_tb_reference_files.pl line 189.

**Comment by martinghunt** [comment]
This looks like a problem at the ENA's side. They currently have issues with their FTP site which is making downloads fail. Try again over the next few days and hopefully it should work.

**Comment by dhcvn** [comment]
Hi, after several days I still got these errors. Do you think of another issue?

**Comment by martinghunt** [comment]
Yes, it turns out there were other issues, which I just fixed. If you use the latest code then it will work (I ran this morning and it was ok).
I've also put a singularity build of the latest code, and an archive of the output of the download script here:
https://drive.google.com/drive/folders/1j8xyNro-AUHxtpIyrYq9MpTDHY-mKZ7K?usp=sharing

**Comment by dhcvn** [comment]
I copied above img and it's worked. Thanks for your time supporting me.
Best wishes,

**Comment by NgocNam1512** [comment]
Hi,
I have the same error type and want to reopen this issue.
I am not familiar with singularity so I use docker to run the tutorial. When I download the reference genome, I get this error:
`(vgp) namnn12@gen-namnguyen-d:~/tutors/clockwork$ docker run --rm ghcr.io/iqbal-lab-org/clockwork download_tb_reference_files.pl Ref.download
------------------- download genomes --------------------
enaDataGet -d tmp.1 -f fasta JALN00000000
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (5.2.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/bioinf-tools/enaBrowserTools/python3/enaDataGet.py", line 92, in <module>
    sequenceGet.download_wgs(dest_dir, accession, output_format)
  File "/bioinf-tools/enaBrowserTools/python3/sequenceGet.py", line 40, in download_wgs
    return download_unversioned_wgs(dest_dir, accession, output_format)
  File "/bioinf-tools/enaBrowserTools/python3/sequenceGet.py", line 57, in download_unversioned_wgs
    public_set_url = utils.get_nonversioned_wgs_ftp_url(prefix, utils.PUBLIC, output_format)
  File "/bioinf-tools/enaBrowserTools/python3/utils.py", line 461, in get_nonversioned_wgs_ftp_url
    ftp = ftplib.FTP(ftp_url)
  File "/usr/lib/python3.8/ftplib.py", line 119, in __init__
    self.connect(host)
  File "/usr/lib/python3.8/ftplib.py", line 158, in connect
    self.welcome = self.getresp()
  File "/usr/lib/python3.8/ftplib.py", line 240, in getresp
    resp = self.getmultiline()
  File "/usr/lib/python3.8/ftplib.py", line 226, in getmultiline
    line = self.getline()
  File "/usr/lib/python3.8/ftplib.py", line 214, in getline
    raise EOFError
EOFError
ERROR: Something unexpected went wrong please try again.
If problem persists, please contact ENA (https://www.ebi.ac.uk/ena/browser/support) for assistance, with the above error details.
Checking availability of https://www.ebi.ac.uk/ena/browser/api/fasta/JALN00000000
Error running: enaDataGet -d tmp.1 -f fasta JALN00000000 at /clockwork/scripts/download_tb_reference_files.pl line 189.
`
I want to call variants for Mycobacterium tuberculosis. I searched and downloaded its genome (NC_000962.3.fa) but in the next step (Index the decontamination reference) I couldn't find the 'Ref.download/remove_contam.tsv' file. 
Could you please help me fix this error or tell me where to download this file?
