### ISSUE TITLE
Error connecting to database

### ISSUE THREAD

**Issue by pedrodcb** [iqbal-lab-org/clockwork#97]
Hello, I’m following your instructions for the Walkthrough: using tracking database and I seem to be encountering the error below when I try to run the following command:

`singularity exec clockwork_v0.11.1.img clockwork make_empty_db db.ini`

```
Error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.11.1-py3.8.egg/clockwork/db_maker.py", line 7, in __init__
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.11.1-py3.8.egg/clockwork/db_connection.py", line 7, in __init__
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.11.1-py3.8.egg/clockwork/db_connection.py", line 50, in _parse_config_file
  File "/usr/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'db_login'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/clockwork", line 4, in <module>
    __import__('pkg_resources').run_script('clockwork==0.11.1', 'clockwork')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.11.1-py3.8.egg/EGG-INFO/scripts/clockwork", line 1019, in <module>
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.11.1-py3.8.egg/clockwork/tasks/make_empty_db.py", line 5, in run
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.11.1-py3.8.egg/clockwork/db_maker.py", line 9, in __init__
Exception: Error connecting to database
```

I’m pretty confident about the contents of my **db.ini** file. They really follow what you’ve given as an example here:
```
[db_login]
user = xxxxxxxx
password = xxxxxxxxx
host = locahost
db = clockwork_db
```

Would you have any idea what could be going on and what I can do to solve this? Is the problem on your end or mine? Any insight will be most appreciated thank you!

**Comment by martinghunt** [comment]
It might be that singularity is set up in a way that means it can't see the db.ini file. Could you try the fix at the end of this comment?
https://github.com/iqbal-lab-org/clockwork/issues/83#issuecomment-1164535433
